---
- name: Déploiement Cloud Étudiant - Orchestrateur
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    guac_url: "http://172.16.180.250:8080/guacamole"
    guac_admin: "guacadmin"
    guac_pass: "guacadmin"

    templates_os:
      UbuntuServ: 106
      Win10: 107

  tasks:
    - name: Installer proxmoxer
      pip: 
        name: proxmoxer
        state: present

    - name: Lancer la création Linux
      include_tasks: tasks/create_linux.yml
      vars:
        template_id: "{{ templates_os[item] }}"
      loop: "{{ [choix_os] | flatten }}"
      when: item in ['UbuntuServ', 'Debian']

    - name: Lancer la création Windows
      include_tasks: tasks/create_windows.yml
      vars:
        template_id: "{{ templates_os[item] }}"
      loop: "{{ [choix_os] | flatten }}"
      when: item in ['Win10', 'WinServer']

    - name: Ajouter les machines
      add_host:
        name: "172.16.205.{{ vmid_etudiant }}"
        groups: "new_vms"
        ansible_user: "etu"
        ansible_password: "etu"
        ansible_become_password: "etu"

    - name: Lancer la configuration Guacamole Linux
      include_tasks: tasks/guac_linux.yml
      loop: "{{ [choix_os] | flatten }}"
      when: item in ['UbuntuServ', 'Debian']

    - name: Lancer la configuration Guacamole Windows
      include_tasks: tasks/guac_windows.yml
      loop: "{{ [choix_os] | flatten }}"
      when: item in ['Win10', 'WinServer'] 

    - name: "[Guacamole] Créer le compte etu"
      scicore.guacamole.guacamole_user:
        base_url: "{{ guac_url }}"
        auth_username: "{{ guac_admin }}"
        auth_password: "{{ guac_pass }}"
        username: "etu_{{ vmid_etudiant }}"
        password: "etu"
        allowed_connections:
          - "SSH_Linux_{{ vmid_etudiant }}"
          - "RDP_Windows_{{ vmid_etudiant }}"
        validate_certs: false
        state: present