---
# ==============================================================
# JEU 1 : PROXMOX (Création de la machine depuis AWX)
# ==============================================================
- name: Déploiement Cloud Étudiant - Phase Création
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Installer proxmoxer (le traducteur Python pour l'API)
      pip:
        name: proxmoxer
        state: present

    # --- ÉTAPE 1 : CLONER ET CONFIGURER (SANS ALLUMER) ---
    - name: Cloner la VM Template et injecter Cloud-Init
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "exbasis"
        
        # Source
        vmid: 102              
        clone: "VMtest"        
        # Destination
        newid: "{{ newid }}"   
        name: "{{ new_vm_name }}"
        full: false            # Clone rapide (2 secondes)
        
        state: present         # <--- LE SECRET : On crée, on n'allume pas !
        
        # Configuration Cloud-Init
        ciuser: "etudiant"
        cipassword: "password123"
        ipconfig:
          ipconfig0: "ip=172.16.1.{{ newid }}/24,gw=172.16.1.1" 

    # --- ÉTAPE 2 : ALLUMER LA NOUVELLE VM ---
    - name: Démarrer la nouvelle VM
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "exbasis"
        vmid: "{{ newid }}"    # On cible uniquement la nouvelle machine
        state: started         # Et on l'allume !

    - name: Ajouter la nouvelle VM à l'inventaire temporaire
      add_host:
        name: "172.16.1.{{ newid }}"
        groups: nouvelles_vms
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

# ==============================================================
# JEU 2 : NOUVELLE VM (Configuration par SSH)
# ==============================================================
- name: Configuration de l'environnement étudiant
  hosts: nouvelles_vms      
  remote_user: "etudiant"   
  become: false             # <--- ON DESACTIVE SUDO TEMPORAIREMENT
  gather_facts: false       

  tasks:
    - name: Attendre que la VM soit démarrée et SSH disponible
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: DIAGNOSTIC 1 - Vérifier qui je suis
      raw: whoami
      register: test_user

    - name: DIAGNOSTIC 2 - Chercher où est caché sudo
      raw: whereis sudo
      register: test_sudo

    - name: DIAGNOSTIC 3 - Afficher le chemin de l'environnement ($PATH)
      raw: echo $PATH
      register: test_path

    - name: Afficher les résultats de l'enquête
      debug:
        msg: 
          - "Je suis connecté en tant que : {{ test_user.stdout_lines[0] }}"
          - "Le système voit sudo ici : {{ test_sudo.stdout_lines[0] }}"
          - "Mon $PATH actuel est : {{ test_path.stdout_lines[0] }}"