---
# ==============================================================
# JEU 1 : PROXMOX (Création de la machine depuis AWX)
# ==============================================================
- name: Déploiement Cloud Étudiant - Phase Création
  hosts: all
  gather_facts: false
  
  tasks:
    - name: Installer proxmoxer (le traducteur Python pour l'API)
      pip:
        name: proxmoxer
        state: present

    - name: Cloner la VM Template
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "exbasis"
        vmid: 102
        newid: "{{ newid }}"
        name: "{{ new_vm_name }}"
        clone: true
        full: false
        timeout: 600
        state: started 
        ciuser: "etudiant"
        cipassword: "password123"
        ipconfig:
          ipconfig0: "ip=172.16.1.{{ newid }}/24,gw=172.16.1.1" 

    - name: Ajouter la nouvelle VM à l'inventaire temporaire
      add_host:
        name: "172.16.1.{{ newid }}"
        groups: nouvelles_vms
        ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

- name: Configuration de l'environnement étudiant
  hosts: nouvelles_vms      
  remote_user: "etudiant"   
  become: true             
  gather_facts: true       

  tasks:
    - name: Attendre que la VM soit démarrée et SSH disponible
      wait_for_connection:
        delay: 10
        timeout: 300

    - name: Mettre à jour le catalogue des applications (apt update)
      apt:
        update_cache: yes

    - name: Installer l'environnement de base (Nginx et Python)
      apt:
        name:
          - nginx
          - python3
          - python3-pip
        state: present

    - name: S'assurer que le serveur Web Nginx est allumé
      service:
        name: nginx
        state: started
        enabled: yes