---
- name: Démarrage d'une VM (Self-Service)
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Installer proxmoxer
      pip:
        name: proxmoxer
        state: present

    - name: Démarrer la VM Linux
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "exbasis"
        vmid: "200{{ vmid_etudiant }}"
        validate_certs: false
        state: started
      when: "'UbuntuServ' in choix_os or 'Debian' in choix_os"
      no_log: true
      ignore_errors: true

    - name: Démarrer la VM Windows
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "exbasis"
        vmid: "300{{ vmid_etudiant }}"
        validate_certs: false
        state: started
      when: "'Win10' in choix_os or 'WinServer' in choix_os"
      no_log: true
      ignore_errors: true