---
- name: Eteindre une VM (Self-Service)
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Vérifier que choix_os est défini
      assert:
        that:
          - choix_os is defined
          - choix_os in ['Linux', 'Windows']
        fail_msg: "La variable 'choix_os' doit être définie avec la valeur 'Linux' ou 'Windows'"

    - name: Installer proxmoxer
      pip:
        name: proxmoxer
        state: present

    - name: Eteindre la VM Linux
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "pve"
        vmid: "200{{ vmid_etudiant }}"
        validate_certs: false
        state: stopped
      when: "'Linux' in choix_os"
      no_log: true
      ignore_errors: true

    - name: Eteindre la VM Windows
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "pve"
        vmid: "300{{ vmid_etudiant }}"
        validate_certs: false
        state: stopped
      when: "'Windows' in choix_os"
      no_log: true
      ignore_errors: true