- name: Suppression d'une VM existante
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Installer proxmoxer
      pip:
        name: proxmoxer
        state: present

    - name: Eteindre la VM (windows)
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "nimbus14"
        vmid: "300{{ vmid_etudiant }}"
        validate_certs: false
        state: stopped
        force: true
      ignore_errors: true
      when: "'Windows' in choix_os" 

    - name: Eteindre la VM (linux)
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "nimbus14"
        vmid: "200{{ vmid_etudiant }}"
        validate_certs: false
        state: stopped
        force: true
      ignore_errors: true
      when: "'Linux' in choix_os or 'Debian' in choix_os" 

    - name: Supprimer la VM (Linux)
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "nimbus14"
        vmid: "200{{ vmid_etudiant }}"
        validate_certs: false
        state: absent
      ignore_errors: true
      when: "'Linux' in choix_os"

    - name: Supprimer la VM (Windows)
      community.proxmox.proxmox_kvm:
        api_host: "{{ pve_api_host }}"
        api_user: "root@pam"
        api_token_id: "{{ pve_api_token_id }}"
        api_token_secret: "{{ pve_api_token_secret }}"
        node: "nimbus14"
        vmid: "300{{ vmid_etudiant }}"
        validate_certs: false
        state: absent
      ignore_errors: true
      when: "'Windows' in choix_os"

    - name: Supprimer la connexion Guacamole (Linux)
      scicore.guacamole.guacamole_connection:
        base_url: "http://{{ guac_host }}:8080/guacamole" 
        auth_username: "{{ guac_admin }}"
        auth_password: "{{ guac_pass }}"
        connection_name: "SSH_Linux_{{ vmid_etudiant }}"
        validate_certs: false
        state: absent
      ignore_errors: true
      when: "'Linux' in choix_os"

    - name: Supprimer la connexion Guacamole (Windows)
      scicore.guacamole.guacamole_connection:
        base_url: "http://{{ guac_host }}:8080/guacamole"
        auth_username: "{{ guac_admin }}"
        auth_password: "{{ guac_pass }}"
        connection_name: "RDP_Windows_{{ vmid_etudiant }}"
        validate_certs: false
        state: absent
      ignore_errors: true
      when: "'Windows' in choix_os"