---
- name: "[Guacamole] Créer la connexion RDP (Windows)"
  scicore.guacamole.guacamole_connection:
    base_url: "{{ guac_url }}"
    auth_username: "{{ guac_admin }}"
    auth_password: "{{ guac_pass }}"
    connection_name: "RDP_Windows_{{ vmid_etudiant }}"
    protocol: "rdp"
    hostname: "172.16.205.{{ vmid_etudiant }}"
    port: 3389
    username: "etu"
    password: "etu"
    rdp_security: "nla"
    rdp_ignore_server_certs: true
    validate_certs: false
    state: present